all:
	gcc -I /home/juniarto/mongodbdriver/src --std=c99 ../*.c x.c -o x
	gcc -I /home/juniarto/mongodbdriver/src --std=c99 ../*.c insert.c -o insert
	gcc -I /home/juniarto/mongodbdriver/src --std=c99 ../*.c query.c -o query
